# Generated by Django 3.0.5 on 2020-05-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoIndication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('href', models.TextField()),
                ('status', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('geo_loc_original', models.TextField()),
                ('target', models.TextField()),
                ('original', models.IntegerField()),
                ('geo_loc_keywords', models.TextField()),
                ('geo_loc_polygon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('href', models.TextField()),
                ('status', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('geo_loc_original', models.TextField()),
                ('manufacturer', models.TextField()),
                ('mainId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.GeoIndication')),
            ],
        ),
    ]
