# Generated by Django 3.0.5 on 2020-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoindication',
            name='original',
        ),
        migrations.RemoveField(
            model_name='manufacturers',
            name='geo_loc_original',
        ),
        migrations.AlterField(
            model_name='geoindication',
            name='geo_loc_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoindication',
            name='geo_loc_polygon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoindication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geoindication',
            name='status',
            field=models.TextField(choices=[('Действует', 'Действует'), ('Прекратил действие', 'Прекратил действие'), ('Нет данных', 'Нет данных'), ('Срок действия истек', 'Срок действия истек')]),
        ),
        migrations.AlterField(
            model_name='geoindication',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='status',
            field=models.TextField(choices=[('Действует', 'Действует'), ('Прекратил действие', 'Прекратил действие'), ('Нет данных', 'Нет данных'), ('Срок действия истек', 'Срок действия истек')]),
        ),
    ]
