# Generated by Django 3.0.5 on 2020-05-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200521_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoindication',
            name='geo_loc_keywords',
        ),
    ]
