# Generated by Django 3.0.5 on 2020-05-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20190522_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoIndication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('href', models.TextField()),
                ('status', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('geo_loc_original', models.TextField()),
                ('target', models.TextField()),
                ('original', models.IntegerField()),
                ('geo_loc_keywords', models.TextField()),
                ('geol_loc_polygon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('href', models.TextField()),
                ('status', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('geo_loc_original', models.TextField()),
                ('manufacturer', models.TextField()),
                ('mainId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.GeoIndication')),
            ],
        ),
    ]
