# Generated by Django 3.0.5 on 2020-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_geoindication_manufacturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
