# Generated by Django 3.0.5 on 2020-05-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20200505_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoindication',
            old_name='geol_loc_polygon',
            new_name='geo_loc_polygon',
        ),
    ]
