# Generated by Django 3.0.5 on 2020-05-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20200505_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
